name: Deploy to EC2

on:
  push:
    branches:
      - main # Or your default branch name
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/upskill.pem
          chmod 600 ~/.ssh/upskill.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/upskill.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
            cd UPSKILL-Backend &&
            git pull &&
            npm i &&
            pm2 restart 1
          '
